### ISSUE TITLE
Cannot find some packages

### ISSUE THREAD

**Issue by gautica** [arminstr/ros_scenario_simulation#9]
Hi, I am currently studying your source code, but it is difficult to make it run due to required packages. Especially I cannot find the package **op_waypoint_follower**. I installed **OpenPlanner** from core_planning repo from Autoware.AI. But it doesn't have this package. Can you tell me where you installed OpenPlanner and probably other packages. Thank you

**Comment by arminstr** [comment]
Hi, I added a repository containing a Dockerfile and install instructions. This also includes a *.repos file with the dependencies for OpenPlanner. You can find it here: [https://github.com/arminstr/ros_ci_docker](https://github.com/arminstr/ros_ci_docker)
Hope this helps!

**Comment by gautica** [comment]
thanks, but I see, there is a package called ff_waypoint_follower not op_waypoint_follower. Should I change code to adopt that?

**Comment by gautica** [comment]
I had another strange problem. I compiled ad-xolib without any error. But when i run catkin build to compile packages, i got this error message:
**src/scenario_goal/../open_scenario_helper/include/ad-xolib/src/xosc/xosc.h:27:9: error: ‘t_patternstr’ does not name a type
 typedef t_patternstr<parameter_pattern> parameter;**
Do you know why it happened?
Actually I successfully build it before. But this time I had errors.
